version: '3.8'

services:
  easy-share-files:
    image: nginx:alpine
    container_name: easy-share-files
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./share:/usr/share/nginx/html
    ports: ["23000:80"]
